Algoritmo "FuncaoMultiParametro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/10/2021
Funcao multi(x,y:inteiro):inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   retorne x * y
fimfuncao
Var
n,m,res: inteiro
Inicio
n <- 4
m <- -9
res<- multi(n,m)
escreva(res)

Fimalgoritmo